ENH: Use name property in meta file sequence reader
IGSIO/SlicerIGSIO pull request #12
Opened 2022-01-05 23:15 UTC by nathanbmnt

I have a program where users can load .seq.mha's one at a time. My program reads meta info in those mha's and groups the sequence images accordingly into one sequence browser. Unfortunately every time a new sequence file is loaded, a new browser is created, so I end up having to write a lot of code to delete the browser, then add the sequence nodes to the compilation browser, then delete the proxy nodes that are automatically created when `AddSynchronizedSequenceNode` is called.

I've noticed that when loading .seq.nrrd's the "name" property is used in that reader.
![image](https://user-images.githubusercontent.com/40271210/148302841-c9568c08-e847-4768-b747-09d39d2dcdb8.png)

This PR adds the ability to import a sequence metafile with the name property set. The browser, image proxy, and image sequence nodes will use this name. If a browser exists with that name the new sequences will be added to it.
![image](https://user-images.githubusercontent.com/40271210/148303080-f4a78a58-4202-409d-9fa1-0acf8805c1f9.png)

I'm also open to instead having a property like "browserID" to explicitly define the browser?

2022-01-06 14:01 UTC, lassoan requested changes
Thank you, this would be useful. Some small improvements are needed - see details inline.

2022-01-06 14:01 UTC, lassoan commented on MetafileImporter/Logic/vtkSlicerMetafileImporterLogic.cxx
> +const qSlicerFileReader::IOProperties& properties/*=IOProperties()*/)
Qt must not be used in logic classes. I would recommend this API instead:

vtkMRMLSequenceBrowserNode* vtkSlicerMetafileImporterLogic::ReadSequenceFile(const std::string& fileName, vtkCollection* addedSequenceNodes/*=nullptr*/, const char* outputBrowserNodeID/*=nullptr*/)

2022-01-06 14:01 UTC, lassoan commented on MetafileImporter/qSlicerMetafileReader.cxx
> +  vtkMRMLSequenceBrowserNode* browserNode = d->MetafileImporterLogic->ReadSequenceFile(fileName.toStdString(), loadedSequenceNodes.GetPointer(), properties);
Please add a node selector to the reader options widget to optionally select a browser node. Similarly how you can select a color node when you load a volume in [volume loading options widget](https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/Volumes/qSlicerVolumesIOOptionsWidget.cxx).

2022-01-10 22:27 UTC, nathanbmnt commented on MetafileImporter/qSlicerMetafileReader.cxx
> +  vtkMRMLSequenceBrowserNode* browserNode = d->MetafileImporterLogic->ReadSequenceFile(fileName.toStdString(), loadedSequenceNodes.GetPointer(), properties);
Where is this reader options widget?

2022-01-10 22:27 UTC, nathanbmnt commented
Closing this PR in favor of a new PR which just adds a outputBrowserNodeID argument. https://github.com/IGSIO/SlicerIGSIO/pull/13

2022-01-10 22:27 UTC, closed without merging